# Serving HTML through API Gateway for AWS Lambda
service: night 

plugins:
  - serverless-offline
  - serverless-plugin-optimize

package:
  individually: true

custom:
  serverless-offline:
    babelOptions:
      presets: ["es2015", "stage-2"]
  optimize:
    debug: true

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  home:
    handler: home.home
    events:
      - http:
          method: get
          path: /
  stripe:
    handler: stripe.stripe
    events:
      - http:
          method: get
          path: stripe 


resources:
  Resources:
    zergS3:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
    zergBP:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: zergS3
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: zergS3 
                  - "/*"
    zergCF:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
          - DomainName:
              Fn::GetAtt:
              - zergS3
              - DomainName
            Id: myS3Origin
            S3OriginConfig: {}
          Enabled: 'true'
          DefaultCacheBehavior:
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: 'false'
            ViewerProtocolPolicy: allow-all
