# Nightshell.com blog portfolio website 
service: night 

plugins:
  - serverless-offline
  - serverless-plugin-optimize

package:
  individually: true

custom:
  serverless-offline:
    babelOptions:
      presets: ["es2015", "stage-2"]
  optimize:
    debug: true

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: dev

functions:
  home:
    handler: home.home
    events:
      - http:
          method: get
          path: /
  stripe:
    handler: stripe.stripe
    events:
      - http:
          method: get
          path: stripe 

resources:
  Resources:
    mazdas3:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
    mazdabp:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: mazdas3
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: mazdas3 
                  - "/*"
    mazdacf:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
          - DomainName:
              Fn::GetAtt:
              - mazdas3
              - DomainName
            Id: myS3Origin
            S3OriginConfig: {}
          Enabled: 'true'
          DefaultCacheBehavior:
            TargetOriginId: myS3Origin
            Compress: 'true'
            ForwardedValues:
              QueryString: 'false'
            ViewerProtocolPolicy: allow-all
