# Serving HTML through API Gateway for AWS Lambda
service: night 

plugins:
  - serverless-offline
  - serverless-plugin-optimize

package:
  individually: true

custom:
  serverless-offline:
    babelOptions:
      presets: ["es2015", "stage-2"]
  optimize:
    debug: true

provider:
  name: aws
  runtime: nodejs4.3

functions:
  night:
    handler: handler.html
    events:
      - http:
          method: get
          path: /
